version: "3"
name: new-website-api

services:
  db:
    container_name: new-website-api-db
    platform: linux/x86_64
    build:
      context: .
      dockerfile: db/Dockerfile
    restart: always
    tty: true
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    volumes:
      - ./db/my.cnf:/etc/mysql/my.cnf
      - ./db/init:/docker-entrypoint-initdb.d
    networks:
      - internal
      - new-website-api-phpmyadmin

  phpmyadmin:
    container_name: new-website-api-phpmyadmin
    depends_on:
      - db
    image: phpmyadmin
    restart: always
    tty: true
    ports:
      - ${PORT_DB}:80
    environment:
      PMA_HOST: db
      UPLOAD_LIMIT: 25M
    volumes:
      # Phpmyadmin configuration files
      - ./configurations/phpmyadmin/config.inc.php:/etc/phpmyadmin/config.inc.php
      - ./configurations/phpmyadmin/config.secret.inc.php:/etc/phpmyadmin/config.secret.inc.php
    networks:
      - new-website-api-phpmyadmin

  mkdocs:
    container_name: new-website-api-mkdocs
    restart: no
    build:
      context: .
      dockerfile: mkdocs/Dockerfile
    command:
      - /bin/bash
      - -c
      - |
        mkdocs build
        rm -rf /var/www/src/src/main/resources/site
        mv site /var/www/src/src/main/resources
    working_dir: /var/www/src
    volumes:
      - ../:/var/www/src

  gradle:
    container_name: new-website-api-kotlin-build
    restart: no
    depends_on:
      - mkdocs
    build:
      context: .
      dockerfile: gradle/Dockerfile
    command:
      - /bin/bash
      - -c
      - |
        rm -rf /var/www/src/src/main/resources/api
        gradle dokkaHtmlMultiModule
        mv -f api /var/www/src/src/main/resources
        gradle buildFatJar
    working_dir: /var/www/src
    volumes:
      - ../:/var/www/src

  java:
    container_name: new-website-api-server-run
    build:
      context: .
      dockerfile: java/Dockerfile
    restart: always
    tty: true
    command: "java -jar build/libs/VZ-API.jar"
    ports:
      - ${PORT_API}:3000
    working_dir: /var/www/src
    volumes:
      - ../:/var/www/src
      # Server configuration files
      - ./configurations/server:/var/www/src/configuration
    networks:
      - internal
    healthcheck:
      test: bash -c "[ -f /var/www/src/build/libs/VZ-API.jar ]"
      interval: 10s
      timeout: 60s
      retries: 5

networks:
  new-website-api-phpmyadmin:
  internal:
    driver: bridge

volumes:
  new-website-api-db:
