##########################
## VERSIONS
##########################

[versions]
## https://mvnrepository.com/artifact/mysql/mysql-connector-java
mysqlConnectorVersion="8.0.30"
## https://flywaydb.org/documentation/learnmore/releaseNotes
flywayVersion="9.1.3"
## https://github.com/brettwooldridge/HikariCP/tags
hikariCpVersion="5.0.1"
## https://github.com/JetBrains/Exposed/releases
exposedVersion="0.39.2"

##########################
## LIBRARIES
##########################

[libraries.mysql_connector_java]
module = "mysql:mysql-connector-java"
[libraries.mysql_connector_java.version]
ref = "mysqlConnectorVersion"

[libraries.hikari]
module = "com.zaxxer:HikariCP"
[libraries.hikari.version]
ref = "hikariCpVersion"

[libraries.exposed_core]
module = "org.jetbrains.exposed:exposed-core"
[libraries.exposed_core.version]
ref = "exposedVersion"

[libraries.exposed_dao]
module = "org.jetbrains.exposed:exposed-dao"
[libraries.exposed_dao.version]
ref = "exposedVersion"

[libraries.exposed_jdbc]
module = "org.jetbrains.exposed:exposed-jdbc"
[libraries.exposed_jdbc.version]
ref = "exposedVersion"

[libraries.flyway_core]
module = "org.flywaydb:flyway-core"
[libraries.flyway_core.version]
ref = "flywayVersion"

[libraries.flyway_mysql]
module = "org.flywaydb:flyway-mysql"
[libraries.flyway_mysql.version]
ref = "flywayVersion"

##########################
## BUNDLES
##########################

[bundles]
database = [
    "mysql_connector_java",
    "hikari",
    "exposed_core",
    "exposed_dao",
    "exposed_jdbc",
    "flyway_core",
    "flyway_mysql",
]
