# modules
[libraries.koin_ktor]
module = "io.insert-koin:koin-ktor"
[libraries.logback]
module = "ch.qos.logback:logback-classic"

# versions
[libraries.koin_ktor.version]
ref = "koinVersion"
[libraries.logback.version]
ref = "logbackVersion"

[bundles]
other = [
    "koin_ktor",
    "logback",
]